// Comprehensive actions for popular integrations
// Each popular integration has 10-20+ specific actions

import { IntegrationAction } from "./integrations-full-data";

export const comprehensiveActions: Record<string, IntegrationAction[]> = {
  gmail: [
    { id: "gmail_send", name: { fr: "Envoyer un email", en: "Send Email" }, description: { fr: "Envoie un nouvel email", en: "Send a new email" }, prompt: { fr: "Envoie un email Gmail à [destinataire] avec sujet [sujet] et contenu : [corps du message]", en: "Send a Gmail email to [recipient] with subject [subject] and content: [message body]" } },
    { id: "gmail_send_reply", name: { fr: "Répondre à un email", en: "Reply to Email" }, description: { fr: "Répond à un email existant", en: "Reply to an existing email" }, prompt: { fr: "Réponds à l'email [thread_id] avec : [contenu de la réponse]", en: "Reply to email [thread_id] with: [reply content]" } },
    { id: "gmail_forward", name: { fr: "Transférer un email", en: "Forward Email" }, description: { fr: "Transfère un email à d'autres destinataires", en: "Forward an email to other recipients" }, prompt: { fr: "Transfère l'email [message_id] à [nouveaux destinataires]", en: "Forward email [message_id] to [new recipients]" } },
    { id: "gmail_search", name: { fr: "Rechercher des emails", en: "Search Emails" }, description: { fr: "Recherche des emails avec des critères", en: "Search emails with criteria" }, prompt: { fr: "Recherche les emails Gmail correspondant à : [critères de recherche] (ex: from:user@email.com, subject:facture, is:unread)", en: "Search for Gmail emails matching: [search criteria] (e.g., from:user@email.com, subject:invoice, is:unread)" } },
    { id: "gmail_get_email", name: { fr: "Récupérer un email", en: "Get Email" }, description: { fr: "Récupère le contenu d'un email spécifique", en: "Get the content of a specific email" }, prompt: { fr: "Récupère le contenu de l'email [message_id]", en: "Get the content of email [message_id]" } },
    { id: "gmail_list_emails", name: { fr: "Lister les emails", en: "List Emails" }, description: { fr: "Liste les emails d'un label ou dossier", en: "List emails from a label or folder" }, prompt: { fr: "Liste les [nombre] derniers emails du label [INBOX/SENT/label personnalisé]", en: "List the last [number] emails from label [INBOX/SENT/custom label]" } },
    { id: "gmail_create_draft", name: { fr: "Créer un brouillon", en: "Create Draft" }, description: { fr: "Crée un brouillon d'email", en: "Create an email draft" }, prompt: { fr: "Crée un brouillon Gmail pour [destinataire] avec sujet [sujet] et contenu : [corps]", en: "Create a Gmail draft for [recipient] with subject [subject] and content: [body]" } },
    { id: "gmail_update_draft", name: { fr: "Modifier un brouillon", en: "Update Draft" }, description: { fr: "Modifie un brouillon existant", en: "Update an existing draft" }, prompt: { fr: "Modifie le brouillon [draft_id] avec : [nouvelles modifications]", en: "Update draft [draft_id] with: [new changes]" } },
    { id: "gmail_send_draft", name: { fr: "Envoyer un brouillon", en: "Send Draft" }, description: { fr: "Envoie un brouillon existant", en: "Send an existing draft" }, prompt: { fr: "Envoie le brouillon [draft_id]", en: "Send draft [draft_id]" } },
    { id: "gmail_delete", name: { fr: "Supprimer un email", en: "Delete Email" }, description: { fr: "Supprime un email (corbeille)", en: "Delete an email (trash)" }, prompt: { fr: "Supprime l'email [message_id]", en: "Delete email [message_id]" } },
    { id: "gmail_archive", name: { fr: "Archiver un email", en: "Archive Email" }, description: { fr: "Archive un email", en: "Archive an email" }, prompt: { fr: "Archive l'email [message_id]", en: "Archive email [message_id]" } },
    { id: "gmail_mark_read", name: { fr: "Marquer comme lu", en: "Mark as Read" }, description: { fr: "Marque un email comme lu", en: "Mark an email as read" }, prompt: { fr: "Marque l'email [message_id] comme lu", en: "Mark email [message_id] as read" } },
    { id: "gmail_mark_unread", name: { fr: "Marquer comme non lu", en: "Mark as Unread" }, description: { fr: "Marque un email comme non lu", en: "Mark an email as unread" }, prompt: { fr: "Marque l'email [message_id] comme non lu", en: "Mark email [message_id] as unread" } },
    { id: "gmail_add_label", name: { fr: "Ajouter un label", en: "Add Label" }, description: { fr: "Ajoute un label à un email", en: "Add a label to an email" }, prompt: { fr: "Ajoute le label [nom du label] à l'email [message_id]", en: "Add label [label name] to email [message_id]" } },
    { id: "gmail_remove_label", name: { fr: "Retirer un label", en: "Remove Label" }, description: { fr: "Retire un label d'un email", en: "Remove a label from an email" }, prompt: { fr: "Retire le label [nom du label] de l'email [message_id]", en: "Remove label [label name] from email [message_id]" } },
    { id: "gmail_create_label", name: { fr: "Créer un label", en: "Create Label" }, description: { fr: "Crée un nouveau label", en: "Create a new label" }, prompt: { fr: "Crée un nouveau label Gmail nommé [nom du label]", en: "Create a new Gmail label named [label name]" } },
    { id: "gmail_list_labels", name: { fr: "Lister les labels", en: "List Labels" }, description: { fr: "Liste tous les labels", en: "List all labels" }, prompt: { fr: "Liste tous les labels Gmail disponibles", en: "List all available Gmail labels" } },
    { id: "gmail_get_attachment", name: { fr: "Télécharger une pièce jointe", en: "Download Attachment" }, description: { fr: "Télécharge une pièce jointe", en: "Download an attachment" }, prompt: { fr: "Télécharge la pièce jointe [attachment_id] de l'email [message_id]", en: "Download attachment [attachment_id] from email [message_id]" } },
    { id: "gmail_send_with_attachment", name: { fr: "Envoyer avec pièce jointe", en: "Send with Attachment" }, description: { fr: "Envoie un email avec pièce jointe", en: "Send an email with attachment" }, prompt: { fr: "Envoie un email Gmail à [destinataire] avec sujet [sujet], contenu [corps] et pièce jointe [fichier]", en: "Send a Gmail email to [recipient] with subject [subject], content [body] and attachment [file]" } },
  ],
  
  slack_v2: [
    { id: "slack_send_message", name: { fr: "Envoyer un message", en: "Send Message" }, description: { fr: "Envoie un message dans un canal", en: "Send a message to a channel" }, prompt: { fr: "Envoie un message Slack dans [#canal] : [message]", en: "Send a Slack message to [#channel]: [message]" } },
    { id: "slack_send_dm", name: { fr: "Envoyer un DM", en: "Send Direct Message" }, description: { fr: "Envoie un message privé", en: "Send a direct message" }, prompt: { fr: "Envoie un message privé Slack à [@utilisateur] : [message]", en: "Send a Slack DM to [@user]: [message]" } },
    { id: "slack_reply_thread", name: { fr: "Répondre dans un thread", en: "Reply in Thread" }, description: { fr: "Répond dans un thread existant", en: "Reply to an existing thread" }, prompt: { fr: "Réponds dans le thread [thread_ts] du canal [channel] : [message]", en: "Reply in thread [thread_ts] in channel [channel]: [message]" } },
    { id: "slack_update_message", name: { fr: "Modifier un message", en: "Update Message" }, description: { fr: "Modifie un message existant", en: "Update an existing message" }, prompt: { fr: "Modifie le message [timestamp] dans [channel] avec : [nouveau contenu]", en: "Update message [timestamp] in [channel] with: [new content]" } },
    { id: "slack_delete_message", name: { fr: "Supprimer un message", en: "Delete Message" }, description: { fr: "Supprime un message", en: "Delete a message" }, prompt: { fr: "Supprime le message [timestamp] du canal [channel]", en: "Delete message [timestamp] from channel [channel]" } },
    { id: "slack_add_reaction", name: { fr: "Ajouter une réaction", en: "Add Reaction" }, description: { fr: "Ajoute un emoji en réaction", en: "Add an emoji reaction" }, prompt: { fr: "Ajoute la réaction [emoji] au message [timestamp] dans [channel]", en: "Add reaction [emoji] to message [timestamp] in [channel]" } },
    { id: "slack_create_channel", name: { fr: "Créer un canal", en: "Create Channel" }, description: { fr: "Crée un nouveau canal", en: "Create a new channel" }, prompt: { fr: "Crée un canal Slack nommé [nom] avec la description : [description]", en: "Create a Slack channel named [name] with description: [description]" } },
    { id: "slack_archive_channel", name: { fr: "Archiver un canal", en: "Archive Channel" }, description: { fr: "Archive un canal", en: "Archive a channel" }, prompt: { fr: "Archive le canal [channel_id]", en: "Archive channel [channel_id]" } },
    { id: "slack_invite_user", name: { fr: "Inviter un utilisateur", en: "Invite User" }, description: { fr: "Invite un utilisateur dans un canal", en: "Invite a user to a channel" }, prompt: { fr: "Invite [@utilisateur] dans le canal [channel]", en: "Invite [@user] to channel [channel]" } },
    { id: "slack_list_channels", name: { fr: "Lister les canaux", en: "List Channels" }, description: { fr: "Liste tous les canaux", en: "List all channels" }, prompt: { fr: "Liste tous les canaux Slack (publics/privés)", en: "List all Slack channels (public/private)" } },
    { id: "slack_list_users", name: { fr: "Lister les utilisateurs", en: "List Users" }, description: { fr: "Liste les membres du workspace", en: "List workspace members" }, prompt: { fr: "Liste tous les utilisateurs du workspace Slack", en: "List all users in the Slack workspace" } },
    { id: "slack_set_status", name: { fr: "Définir le statut", en: "Set Status" }, description: { fr: "Définit le statut utilisateur", en: "Set user status" }, prompt: { fr: "Définit le statut Slack : emoji [emoji], texte [texte], expiration [durée]", en: "Set Slack status: emoji [emoji], text [text], expiration [duration]" } },
    { id: "slack_upload_file", name: { fr: "Uploader un fichier", en: "Upload File" }, description: { fr: "Upload un fichier dans un canal", en: "Upload a file to a channel" }, prompt: { fr: "Upload le fichier [fichier] dans [channel] avec le commentaire : [commentaire]", en: "Upload file [file] to [channel] with comment: [comment]" } },
    { id: "slack_set_topic", name: { fr: "Définir le sujet", en: "Set Channel Topic" }, description: { fr: "Définit le sujet d'un canal", en: "Set a channel's topic" }, prompt: { fr: "Définit le sujet du canal [channel] : [nouveau sujet]", en: "Set channel [channel] topic: [new topic]" } },
    { id: "slack_search", name: { fr: "Rechercher des messages", en: "Search Messages" }, description: { fr: "Recherche dans les messages", en: "Search through messages" }, prompt: { fr: "Recherche dans Slack : [terme de recherche]", en: "Search in Slack: [search term]" } },
  ],
  
  notion: [
    { id: "notion_create_page", name: { fr: "Créer une page", en: "Create Page" }, description: { fr: "Crée une nouvelle page", en: "Create a new page" }, prompt: { fr: "Crée une page Notion intitulée [titre] dans [database/parent] avec le contenu : [contenu]", en: "Create a Notion page titled [title] in [database/parent] with content: [content]" } },
    { id: "notion_update_page", name: { fr: "Mettre à jour une page", en: "Update Page" }, description: { fr: "Met à jour les propriétés d'une page", en: "Update page properties" }, prompt: { fr: "Mets à jour la page Notion [page_id] avec : [propriétés à modifier]", en: "Update Notion page [page_id] with: [properties to modify]" } },
    { id: "notion_archive_page", name: { fr: "Archiver une page", en: "Archive Page" }, description: { fr: "Archive une page", en: "Archive a page" }, prompt: { fr: "Archive la page Notion [page_id]", en: "Archive Notion page [page_id]" } },
    { id: "notion_get_page", name: { fr: "Récupérer une page", en: "Get Page" }, description: { fr: "Récupère une page et ses propriétés", en: "Get a page and its properties" }, prompt: { fr: "Récupère le contenu de la page Notion [page_id]", en: "Get the content of Notion page [page_id]" } },
    { id: "notion_query_database", name: { fr: "Requêter une base", en: "Query Database" }, description: { fr: "Recherche dans une base de données", en: "Search in a database" }, prompt: { fr: "Recherche dans la base Notion [database_id] les entrées où [propriété] [opérateur] [valeur], trié par [champ]", en: "Search in Notion database [database_id] for entries where [property] [operator] [value], sorted by [field]" } },
    { id: "notion_create_database", name: { fr: "Créer une base", en: "Create Database" }, description: { fr: "Crée une nouvelle base de données", en: "Create a new database" }, prompt: { fr: "Crée une base de données Notion [titre] avec les colonnes : [colonnes et types]", en: "Create a Notion database [title] with columns: [columns and types]" } },
    { id: "notion_update_database", name: { fr: "Modifier une base", en: "Update Database" }, description: { fr: "Modifie les propriétés d'une base", en: "Update database properties" }, prompt: { fr: "Modifie la base Notion [database_id] : [modifications]", en: "Update Notion database [database_id]: [changes]" } },
    { id: "notion_append_block", name: { fr: "Ajouter un bloc", en: "Append Block" }, description: { fr: "Ajoute du contenu à une page", en: "Add content to a page" }, prompt: { fr: "Ajoute à la page Notion [page_id] : [type de bloc] avec contenu [contenu]", en: "Add to Notion page [page_id]: [block type] with content [content]" } },
    { id: "notion_get_block_children", name: { fr: "Récupérer les blocs", en: "Get Block Children" }, description: { fr: "Récupère les blocs enfants", en: "Get child blocks" }, prompt: { fr: "Récupère tous les blocs de la page/bloc Notion [block_id]", en: "Get all blocks from Notion page/block [block_id]" } },
    { id: "notion_delete_block", name: { fr: "Supprimer un bloc", en: "Delete Block" }, description: { fr: "Supprime un bloc", en: "Delete a block" }, prompt: { fr: "Supprime le bloc Notion [block_id]", en: "Delete Notion block [block_id]" } },
    { id: "notion_search", name: { fr: "Rechercher", en: "Search" }, description: { fr: "Recherche dans tout Notion", en: "Search across Notion" }, prompt: { fr: "Recherche dans Notion : [terme de recherche], filtrer par [pages/databases]", en: "Search in Notion: [search term], filter by [pages/databases]" } },
    { id: "notion_list_users", name: { fr: "Lister les utilisateurs", en: "List Users" }, description: { fr: "Liste les utilisateurs du workspace", en: "List workspace users" }, prompt: { fr: "Liste tous les utilisateurs du workspace Notion", en: "List all users in the Notion workspace" } },
    { id: "notion_get_user", name: { fr: "Récupérer un utilisateur", en: "Get User" }, description: { fr: "Récupère les infos d'un utilisateur", en: "Get user info" }, prompt: { fr: "Récupère les informations de l'utilisateur Notion [user_id]", en: "Get information for Notion user [user_id]" } },
    { id: "notion_add_comment", name: { fr: "Ajouter un commentaire", en: "Add Comment" }, description: { fr: "Ajoute un commentaire à une page", en: "Add a comment to a page" }, prompt: { fr: "Ajoute un commentaire à la page Notion [page_id] : [commentaire]", en: "Add a comment to Notion page [page_id]: [comment]" } },
  ],
  
  google_sheets: [
    { id: "gsheets_add_row", name: { fr: "Ajouter une ligne", en: "Add Row" }, description: { fr: "Ajoute une nouvelle ligne", en: "Add a new row" }, prompt: { fr: "Ajoute une ligne dans Google Sheets [spreadsheet_id] feuille [sheet_name] avec : [col1: val1, col2: val2]", en: "Add a row to Google Sheets [spreadsheet_id] sheet [sheet_name] with: [col1: val1, col2: val2]" } },
    { id: "gsheets_get_values", name: { fr: "Lire des cellules", en: "Get Values" }, description: { fr: "Lit les valeurs d'une plage", en: "Read values from a range" }, prompt: { fr: "Lis les valeurs de Google Sheets [spreadsheet_id] plage [A1:Z100]", en: "Read values from Google Sheets [spreadsheet_id] range [A1:Z100]" } },
    { id: "gsheets_update_row", name: { fr: "Mettre à jour une ligne", en: "Update Row" }, description: { fr: "Met à jour une ligne existante", en: "Update an existing row" }, prompt: { fr: "Mets à jour la ligne [numéro] de Google Sheets [spreadsheet_id] avec : [nouvelles valeurs]", en: "Update row [number] in Google Sheets [spreadsheet_id] with: [new values]" } },
    { id: "gsheets_update_cell", name: { fr: "Modifier une cellule", en: "Update Cell" }, description: { fr: "Modifie une cellule spécifique", en: "Update a specific cell" }, prompt: { fr: "Modifie la cellule [A1] de [spreadsheet_id] feuille [sheet] avec : [valeur]", en: "Update cell [A1] in [spreadsheet_id] sheet [sheet] with: [value]" } },
    { id: "gsheets_delete_row", name: { fr: "Supprimer une ligne", en: "Delete Row" }, description: { fr: "Supprime une ligne", en: "Delete a row" }, prompt: { fr: "Supprime la ligne [numéro] de [spreadsheet_id] feuille [sheet]", en: "Delete row [number] from [spreadsheet_id] sheet [sheet]" } },
    { id: "gsheets_clear_range", name: { fr: "Effacer une plage", en: "Clear Range" }, description: { fr: "Efface le contenu d'une plage", en: "Clear content of a range" }, prompt: { fr: "Efface le contenu de la plage [A1:Z100] dans [spreadsheet_id]", en: "Clear content of range [A1:Z100] in [spreadsheet_id]" } },
    { id: "gsheets_create_spreadsheet", name: { fr: "Créer un classeur", en: "Create Spreadsheet" }, description: { fr: "Crée un nouveau classeur", en: "Create a new spreadsheet" }, prompt: { fr: "Crée un nouveau classeur Google Sheets nommé [titre]", en: "Create a new Google Sheets spreadsheet named [title]" } },
    { id: "gsheets_add_sheet", name: { fr: "Ajouter une feuille", en: "Add Sheet" }, description: { fr: "Ajoute une nouvelle feuille", en: "Add a new sheet" }, prompt: { fr: "Ajoute une nouvelle feuille [nom] au classeur [spreadsheet_id]", en: "Add a new sheet [name] to spreadsheet [spreadsheet_id]" } },
    { id: "gsheets_copy_sheet", name: { fr: "Copier une feuille", en: "Copy Sheet" }, description: { fr: "Copie une feuille vers un autre classeur", en: "Copy a sheet to another spreadsheet" }, prompt: { fr: "Copie la feuille [sheet_id] de [source_spreadsheet] vers [destination_spreadsheet]", en: "Copy sheet [sheet_id] from [source_spreadsheet] to [destination_spreadsheet]" } },
    { id: "gsheets_delete_sheet", name: { fr: "Supprimer une feuille", en: "Delete Sheet" }, description: { fr: "Supprime une feuille", en: "Delete a sheet" }, prompt: { fr: "Supprime la feuille [sheet_id] du classeur [spreadsheet_id]", en: "Delete sheet [sheet_id] from spreadsheet [spreadsheet_id]" } },
    { id: "gsheets_find_row", name: { fr: "Rechercher une ligne", en: "Find Row" }, description: { fr: "Trouve une ligne par valeur", en: "Find a row by value" }, prompt: { fr: "Recherche dans [spreadsheet_id] feuille [sheet] la ligne où [colonne] = [valeur]", en: "Search in [spreadsheet_id] sheet [sheet] for row where [column] = [value]" } },
    { id: "gsheets_lookup", name: { fr: "Lookup", en: "Lookup Value" }, description: { fr: "Recherche et retourne une valeur", en: "Search and return a value" }, prompt: { fr: "Dans [spreadsheet_id], recherche [valeur] dans colonne [A] et retourne la valeur de colonne [B]", en: "In [spreadsheet_id], lookup [value] in column [A] and return value from column [B]" } },
    { id: "gsheets_format_cells", name: { fr: "Formater des cellules", en: "Format Cells" }, description: { fr: "Applique un formatage aux cellules", en: "Apply formatting to cells" }, prompt: { fr: "Formate la plage [A1:B10] dans [spreadsheet_id] : [options de formatage]", en: "Format range [A1:B10] in [spreadsheet_id]: [formatting options]" } },
    { id: "gsheets_append_row", name: { fr: "Append Row", en: "Append Row" }, description: { fr: "Ajoute une ligne à la fin", en: "Append a row at the end" }, prompt: { fr: "Ajoute à la fin de [spreadsheet_id] feuille [sheet] : [valeurs]", en: "Append to end of [spreadsheet_id] sheet [sheet]: [values]" } },
  ],
  
  openai: [
    { id: "openai_chat", name: { fr: "Chat Completion", en: "Create Chat Completion" }, description: { fr: "Génère une réponse conversationnelle", en: "Generate a conversational response" }, prompt: { fr: "Génère une réponse avec OpenAI GPT pour : [prompt]. Modèle [gpt-4/gpt-3.5-turbo], température [0-1], max_tokens [nombre]", en: "Generate a response with OpenAI GPT for: [prompt]. Model [gpt-4/gpt-3.5-turbo], temperature [0-1], max_tokens [number]" } },
    { id: "openai_image", name: { fr: "Générer une image", en: "Create Image" }, description: { fr: "Génère une image avec DALL-E", en: "Generate an image with DALL-E" }, prompt: { fr: "Génère une image avec DALL-E : [description détaillée]. Taille [1024x1024], qualité [standard/hd], style [vivid/natural]", en: "Generate an image with DALL-E: [detailed description]. Size [1024x1024], quality [standard/hd], style [vivid/natural]" } },
    { id: "openai_edit_image", name: { fr: "Modifier une image", en: "Edit Image" }, description: { fr: "Modifie une image existante", en: "Edit an existing image" }, prompt: { fr: "Modifie l'image [image] selon : [instructions de modification]. Masque : [zone à modifier]", en: "Edit image [image] according to: [edit instructions]. Mask: [area to modify]" } },
    { id: "openai_image_variation", name: { fr: "Variation d'image", en: "Create Image Variation" }, description: { fr: "Crée des variations d'une image", en: "Create variations of an image" }, prompt: { fr: "Crée [nombre] variations de l'image [image]", en: "Create [number] variations of image [image]" } },
    { id: "openai_embedding", name: { fr: "Créer des embeddings", en: "Create Embeddings" }, description: { fr: "Génère des vecteurs d'embedding", en: "Generate embedding vectors" }, prompt: { fr: "Génère des embeddings pour : [texte]. Modèle [text-embedding-ada-002/text-embedding-3-small]", en: "Generate embeddings for: [text]. Model [text-embedding-ada-002/text-embedding-3-small]" } },
    { id: "openai_transcribe", name: { fr: "Transcrire audio", en: "Transcribe Audio" }, description: { fr: "Transcrit un audio avec Whisper", en: "Transcribe audio with Whisper" }, prompt: { fr: "Transcris l'audio [fichier/URL] en texte. Langue : [auto/fr/en]", en: "Transcribe audio [file/URL] to text. Language: [auto/fr/en]" } },
    { id: "openai_translate_audio", name: { fr: "Traduire audio", en: "Translate Audio" }, description: { fr: "Traduit un audio en anglais", en: "Translate audio to English" }, prompt: { fr: "Traduis l'audio [fichier] en anglais", en: "Translate audio [file] to English" } },
    { id: "openai_tts", name: { fr: "Text-to-Speech", en: "Text-to-Speech" }, description: { fr: "Convertit du texte en audio", en: "Convert text to audio" }, prompt: { fr: "Convertis en audio : [texte]. Voix [alloy/echo/fable/onyx/nova/shimmer], vitesse [0.25-4.0]", en: "Convert to audio: [text]. Voice [alloy/echo/fable/onyx/nova/shimmer], speed [0.25-4.0]" } },
    { id: "openai_moderation", name: { fr: "Modération", en: "Content Moderation" }, description: { fr: "Vérifie si le contenu est approprié", en: "Check if content is appropriate" }, prompt: { fr: "Vérifie le contenu : [texte à analyser]", en: "Check content: [text to analyze]" } },
    { id: "openai_fine_tune", name: { fr: "Fine-tuning", en: "Create Fine-tune" }, description: { fr: "Crée un modèle fine-tuné", en: "Create a fine-tuned model" }, prompt: { fr: "Fine-tune un modèle avec le dataset [training_file_id]. Modèle de base [gpt-3.5-turbo]", en: "Fine-tune a model with dataset [training_file_id]. Base model [gpt-3.5-turbo]" } },
    { id: "openai_list_models", name: { fr: "Lister les modèles", en: "List Models" }, description: { fr: "Liste les modèles disponibles", en: "List available models" }, prompt: { fr: "Liste tous les modèles OpenAI disponibles", en: "List all available OpenAI models" } },
    { id: "openai_vision", name: { fr: "Vision (analyse image)", en: "Vision (Image Analysis)" }, description: { fr: "Analyse une image avec GPT-4 Vision", en: "Analyze an image with GPT-4 Vision" }, prompt: { fr: "Analyse l'image [URL/base64] et réponds à : [question sur l'image]", en: "Analyze image [URL/base64] and answer: [question about image]" } },
    { id: "openai_assistant_create", name: { fr: "Créer un Assistant", en: "Create Assistant" }, description: { fr: "Crée un assistant personnalisé", en: "Create a custom assistant" }, prompt: { fr: "Crée un assistant OpenAI : nom [nom], instructions [system prompt], outils [code_interpreter/retrieval/function]", en: "Create an OpenAI assistant: name [name], instructions [system prompt], tools [code_interpreter/retrieval/function]" } },
    { id: "openai_function_call", name: { fr: "Function Calling", en: "Function Calling" }, description: { fr: "Appelle des fonctions via le modèle", en: "Call functions via the model" }, prompt: { fr: "Génère une réponse avec fonction : [prompt]. Fonctions disponibles : [définitions des fonctions JSON]", en: "Generate response with function: [prompt]. Available functions: [function definitions JSON]" } },
  ],
  
  hubspot: [
    { id: "hubspot_create_contact", name: { fr: "Créer un contact", en: "Create Contact" }, description: { fr: "Crée un nouveau contact", en: "Create a new contact" }, prompt: { fr: "Crée un contact HubSpot : email [email], prénom [prénom], nom [nom], téléphone [tel], entreprise [entreprise]", en: "Create a HubSpot contact: email [email], first name [first name], last name [last name], phone [phone], company [company]" } },
    { id: "hubspot_update_contact", name: { fr: "Modifier un contact", en: "Update Contact" }, description: { fr: "Met à jour un contact", en: "Update a contact" }, prompt: { fr: "Mets à jour le contact HubSpot [contact_id/email] avec : [propriétés]", en: "Update HubSpot contact [contact_id/email] with: [properties]" } },
    { id: "hubspot_get_contact", name: { fr: "Récupérer un contact", en: "Get Contact" }, description: { fr: "Récupère les infos d'un contact", en: "Get contact info" }, prompt: { fr: "Récupère le contact HubSpot [contact_id/email]", en: "Get HubSpot contact [contact_id/email]" } },
    { id: "hubspot_search_contacts", name: { fr: "Rechercher des contacts", en: "Search Contacts" }, description: { fr: "Recherche des contacts", en: "Search for contacts" }, prompt: { fr: "Recherche les contacts HubSpot où [propriété] [opérateur] [valeur]", en: "Search HubSpot contacts where [property] [operator] [value]" } },
    { id: "hubspot_create_deal", name: { fr: "Créer une affaire", en: "Create Deal" }, description: { fr: "Crée une nouvelle affaire", en: "Create a new deal" }, prompt: { fr: "Crée une affaire HubSpot : nom [nom], montant [montant], étape [pipeline stage], contact associé [contact_id]", en: "Create a HubSpot deal: name [name], amount [amount], stage [pipeline stage], associated contact [contact_id]" } },
    { id: "hubspot_update_deal", name: { fr: "Modifier une affaire", en: "Update Deal" }, description: { fr: "Met à jour une affaire", en: "Update a deal" }, prompt: { fr: "Mets à jour l'affaire HubSpot [deal_id] : [propriétés à modifier]", en: "Update HubSpot deal [deal_id]: [properties to modify]" } },
    { id: "hubspot_create_company", name: { fr: "Créer une entreprise", en: "Create Company" }, description: { fr: "Crée une nouvelle entreprise", en: "Create a new company" }, prompt: { fr: "Crée une entreprise HubSpot : nom [nom], domaine [domain], secteur [industry]", en: "Create a HubSpot company: name [name], domain [domain], industry [industry]" } },
    { id: "hubspot_create_ticket", name: { fr: "Créer un ticket", en: "Create Ticket" }, description: { fr: "Crée un ticket de support", en: "Create a support ticket" }, prompt: { fr: "Crée un ticket HubSpot : sujet [sujet], description [description], priorité [priority], pipeline [pipeline]", en: "Create a HubSpot ticket: subject [subject], description [description], priority [priority], pipeline [pipeline]" } },
    { id: "hubspot_add_note", name: { fr: "Ajouter une note", en: "Add Note" }, description: { fr: "Ajoute une note à un enregistrement", en: "Add a note to a record" }, prompt: { fr: "Ajoute une note au [contact/deal/company] [id] : [contenu de la note]", en: "Add a note to [contact/deal/company] [id]: [note content]" } },
    { id: "hubspot_create_task", name: { fr: "Créer une tâche", en: "Create Task" }, description: { fr: "Crée une tâche", en: "Create a task" }, prompt: { fr: "Crée une tâche HubSpot : titre [titre], échéance [date], assigné à [owner], associé à [contact/deal id]", en: "Create a HubSpot task: title [title], due [date], assigned to [owner], associated with [contact/deal id]" } },
    { id: "hubspot_send_email", name: { fr: "Envoyer un email", en: "Send Email" }, description: { fr: "Envoie un email via HubSpot", en: "Send an email via HubSpot" }, prompt: { fr: "Envoie un email HubSpot à [contact] : sujet [sujet], contenu [html/texte]", en: "Send a HubSpot email to [contact]: subject [subject], content [html/text]" } },
    { id: "hubspot_enroll_workflow", name: { fr: "Inscrire au workflow", en: "Enroll in Workflow" }, description: { fr: "Inscrit un contact dans un workflow", en: "Enroll a contact in a workflow" }, prompt: { fr: "Inscris le contact [contact_id] dans le workflow [workflow_id]", en: "Enroll contact [contact_id] in workflow [workflow_id]" } },
    { id: "hubspot_list_owners", name: { fr: "Lister les propriétaires", en: "List Owners" }, description: { fr: "Liste les utilisateurs HubSpot", en: "List HubSpot users" }, prompt: { fr: "Liste tous les propriétaires/utilisateurs HubSpot", en: "List all HubSpot owners/users" } },
    { id: "hubspot_add_to_list", name: { fr: "Ajouter à une liste", en: "Add to List" }, description: { fr: "Ajoute un contact à une liste", en: "Add a contact to a list" }, prompt: { fr: "Ajoute le contact [contact_id] à la liste [list_id]", en: "Add contact [contact_id] to list [list_id]" } },
  ],
  
  stripe: [
    { id: "stripe_create_customer", name: { fr: "Créer un client", en: "Create Customer" }, description: { fr: "Crée un nouveau client", en: "Create a new customer" }, prompt: { fr: "Crée un client Stripe : email [email], nom [nom], description [description], métadonnées [metadata]", en: "Create a Stripe customer: email [email], name [name], description [description], metadata [metadata]" } },
    { id: "stripe_update_customer", name: { fr: "Modifier un client", en: "Update Customer" }, description: { fr: "Met à jour un client", en: "Update a customer" }, prompt: { fr: "Mets à jour le client Stripe [customer_id] : [propriétés]", en: "Update Stripe customer [customer_id]: [properties]" } },
    { id: "stripe_create_payment_intent", name: { fr: "Créer un paiement", en: "Create Payment Intent" }, description: { fr: "Crée une intention de paiement", en: "Create a payment intent" }, prompt: { fr: "Crée un paiement Stripe : montant [amount] centimes, devise [currency], client [customer_id]", en: "Create a Stripe payment: amount [amount] cents, currency [currency], customer [customer_id]" } },
    { id: "stripe_confirm_payment", name: { fr: "Confirmer un paiement", en: "Confirm Payment" }, description: { fr: "Confirme une intention de paiement", en: "Confirm a payment intent" }, prompt: { fr: "Confirme le paiement Stripe [payment_intent_id] avec la méthode [payment_method_id]", en: "Confirm Stripe payment [payment_intent_id] with method [payment_method_id]" } },
    { id: "stripe_create_subscription", name: { fr: "Créer un abonnement", en: "Create Subscription" }, description: { fr: "Crée un nouvel abonnement", en: "Create a new subscription" }, prompt: { fr: "Crée un abonnement Stripe : client [customer_id], prix [price_id], essai [trial_days]", en: "Create a Stripe subscription: customer [customer_id], price [price_id], trial [trial_days]" } },
    { id: "stripe_cancel_subscription", name: { fr: "Annuler un abonnement", en: "Cancel Subscription" }, description: { fr: "Annule un abonnement", en: "Cancel a subscription" }, prompt: { fr: "Annule l'abonnement Stripe [subscription_id] (immédiatement/fin de période)", en: "Cancel Stripe subscription [subscription_id] (immediately/end of period)" } },
    { id: "stripe_update_subscription", name: { fr: "Modifier un abonnement", en: "Update Subscription" }, description: { fr: "Met à jour un abonnement", en: "Update a subscription" }, prompt: { fr: "Mets à jour l'abonnement [subscription_id] : nouveau prix [price_id], quantité [qty]", en: "Update subscription [subscription_id]: new price [price_id], quantity [qty]" } },
    { id: "stripe_create_invoice", name: { fr: "Créer une facture", en: "Create Invoice" }, description: { fr: "Crée une facture", en: "Create an invoice" }, prompt: { fr: "Crée une facture Stripe pour [customer_id] avec lignes : [items]", en: "Create a Stripe invoice for [customer_id] with lines: [items]" } },
    { id: "stripe_send_invoice", name: { fr: "Envoyer une facture", en: "Send Invoice" }, description: { fr: "Envoie une facture par email", en: "Send an invoice by email" }, prompt: { fr: "Envoie la facture Stripe [invoice_id] au client", en: "Send Stripe invoice [invoice_id] to customer" } },
    { id: "stripe_create_refund", name: { fr: "Créer un remboursement", en: "Create Refund" }, description: { fr: "Rembourse un paiement", en: "Refund a payment" }, prompt: { fr: "Rembourse le paiement Stripe [charge_id/payment_intent_id], montant [amount] (partiel ou total)", en: "Refund Stripe payment [charge_id/payment_intent_id], amount [amount] (partial or full)" } },
    { id: "stripe_create_product", name: { fr: "Créer un produit", en: "Create Product" }, description: { fr: "Crée un nouveau produit", en: "Create a new product" }, prompt: { fr: "Crée un produit Stripe : nom [nom], description [description], images [urls]", en: "Create a Stripe product: name [name], description [description], images [urls]" } },
    { id: "stripe_create_price", name: { fr: "Créer un prix", en: "Create Price" }, description: { fr: "Crée un prix pour un produit", en: "Create a price for a product" }, prompt: { fr: "Crée un prix Stripe pour [product_id] : montant [amount], devise [currency], récurrence [one_time/recurring]", en: "Create a Stripe price for [product_id]: amount [amount], currency [currency], recurrence [one_time/recurring]" } },
    { id: "stripe_list_charges", name: { fr: "Lister les paiements", en: "List Charges" }, description: { fr: "Liste les paiements", en: "List payments" }, prompt: { fr: "Liste les paiements Stripe du client [customer_id] des [nombre] derniers jours", en: "List Stripe payments for customer [customer_id] from the last [number] days" } },
    { id: "stripe_create_checkout", name: { fr: "Créer une session Checkout", en: "Create Checkout Session" }, description: { fr: "Crée une session de paiement", en: "Create a checkout session" }, prompt: { fr: "Crée une session Checkout Stripe : prix [price_id], mode [payment/subscription], URL succès [url], URL annulation [url]", en: "Create a Stripe Checkout session: price [price_id], mode [payment/subscription], success URL [url], cancel URL [url]" } },
  ],
  
  github: [
    { id: "github_create_issue", name: { fr: "Créer une issue", en: "Create Issue" }, description: { fr: "Crée une nouvelle issue", en: "Create a new issue" }, prompt: { fr: "Crée une issue GitHub dans [owner/repo] : titre [titre], description [description], labels [labels], assignés [assignees]", en: "Create a GitHub issue in [owner/repo]: title [title], description [description], labels [labels], assignees [assignees]" } },
    { id: "github_update_issue", name: { fr: "Modifier une issue", en: "Update Issue" }, description: { fr: "Met à jour une issue", en: "Update an issue" }, prompt: { fr: "Mets à jour l'issue #[number] dans [owner/repo] : [modifications]", en: "Update issue #[number] in [owner/repo]: [changes]" } },
    { id: "github_close_issue", name: { fr: "Fermer une issue", en: "Close Issue" }, description: { fr: "Ferme une issue", en: "Close an issue" }, prompt: { fr: "Ferme l'issue #[number] dans [owner/repo]", en: "Close issue #[number] in [owner/repo]" } },
    { id: "github_add_comment", name: { fr: "Ajouter un commentaire", en: "Add Comment" }, description: { fr: "Ajoute un commentaire", en: "Add a comment" }, prompt: { fr: "Ajoute un commentaire à l'issue/PR #[number] dans [owner/repo] : [commentaire]", en: "Add a comment to issue/PR #[number] in [owner/repo]: [comment]" } },
    { id: "github_create_pr", name: { fr: "Créer une PR", en: "Create Pull Request" }, description: { fr: "Crée une pull request", en: "Create a pull request" }, prompt: { fr: "Crée une PR GitHub dans [owner/repo] de [head] vers [base] : titre [titre], description [description]", en: "Create a GitHub PR in [owner/repo] from [head] to [base]: title [title], description [description]" } },
    { id: "github_merge_pr", name: { fr: "Merger une PR", en: "Merge Pull Request" }, description: { fr: "Merge une pull request", en: "Merge a pull request" }, prompt: { fr: "Merge la PR #[number] dans [owner/repo] avec la méthode [merge/squash/rebase]", en: "Merge PR #[number] in [owner/repo] using [merge/squash/rebase]" } },
    { id: "github_create_branch", name: { fr: "Créer une branche", en: "Create Branch" }, description: { fr: "Crée une nouvelle branche", en: "Create a new branch" }, prompt: { fr: "Crée une branche [nom] dans [owner/repo] depuis [ref/sha]", en: "Create branch [name] in [owner/repo] from [ref/sha]" } },
    { id: "github_create_file", name: { fr: "Créer un fichier", en: "Create File" }, description: { fr: "Crée ou met à jour un fichier", en: "Create or update a file" }, prompt: { fr: "Crée/modifie [path] dans [owner/repo] branche [branch] : contenu [content], message [commit message]", en: "Create/update [path] in [owner/repo] branch [branch]: content [content], message [commit message]" } },
    { id: "github_get_file", name: { fr: "Récupérer un fichier", en: "Get File Contents" }, description: { fr: "Récupère le contenu d'un fichier", en: "Get file contents" }, prompt: { fr: "Récupère le contenu de [path] dans [owner/repo] branche [branch]", en: "Get contents of [path] in [owner/repo] branch [branch]" } },
    { id: "github_list_repos", name: { fr: "Lister les repos", en: "List Repositories" }, description: { fr: "Liste les repos d'un utilisateur/org", en: "List repos for a user/org" }, prompt: { fr: "Liste les repos de [user/org], type [all/owner/member], tri [updated/created]", en: "List repos for [user/org], type [all/owner/member], sort [updated/created]" } },
    { id: "github_create_release", name: { fr: "Créer une release", en: "Create Release" }, description: { fr: "Crée une nouvelle release", en: "Create a new release" }, prompt: { fr: "Crée une release dans [owner/repo] : tag [tag], nom [name], notes [body], prerelease [true/false]", en: "Create a release in [owner/repo]: tag [tag], name [name], notes [body], prerelease [true/false]" } },
    { id: "github_add_labels", name: { fr: "Ajouter des labels", en: "Add Labels" }, description: { fr: "Ajoute des labels à une issue/PR", en: "Add labels to an issue/PR" }, prompt: { fr: "Ajoute les labels [labels] à l'issue/PR #[number] dans [owner/repo]", en: "Add labels [labels] to issue/PR #[number] in [owner/repo]" } },
    { id: "github_request_review", name: { fr: "Demander une review", en: "Request Review" }, description: { fr: "Demande une review sur une PR", en: "Request a review on a PR" }, prompt: { fr: "Demande une review de [reviewers] sur la PR #[number] dans [owner/repo]", en: "Request review from [reviewers] on PR #[number] in [owner/repo]" } },
    { id: "github_dispatch_workflow", name: { fr: "Déclencher un workflow", en: "Dispatch Workflow" }, description: { fr: "Déclenche un workflow GitHub Actions", en: "Trigger a GitHub Actions workflow" }, prompt: { fr: "Déclenche le workflow [workflow_id] dans [owner/repo] branche [ref] avec inputs [inputs]", en: "Trigger workflow [workflow_id] in [owner/repo] branch [ref] with inputs [inputs]" } },
  ],
  
  discord: [
    { id: "discord_send_message", name: { fr: "Envoyer un message", en: "Send Message" }, description: { fr: "Envoie un message dans un canal", en: "Send a message to a channel" }, prompt: { fr: "Envoie un message Discord dans le canal [channel_id] : [message]", en: "Send a Discord message to channel [channel_id]: [message]" } },
    { id: "discord_send_embed", name: { fr: "Envoyer un embed", en: "Send Embed" }, description: { fr: "Envoie un message riche (embed)", en: "Send a rich message (embed)" }, prompt: { fr: "Envoie un embed Discord dans [channel_id] : titre [titre], description [desc], couleur [hex], image [url]", en: "Send a Discord embed to [channel_id]: title [title], description [desc], color [hex], image [url]" } },
    { id: "discord_edit_message", name: { fr: "Modifier un message", en: "Edit Message" }, description: { fr: "Modifie un message existant", en: "Edit an existing message" }, prompt: { fr: "Modifie le message [message_id] dans [channel_id] : [nouveau contenu]", en: "Edit message [message_id] in [channel_id]: [new content]" } },
    { id: "discord_delete_message", name: { fr: "Supprimer un message", en: "Delete Message" }, description: { fr: "Supprime un message", en: "Delete a message" }, prompt: { fr: "Supprime le message [message_id] du canal [channel_id]", en: "Delete message [message_id] from channel [channel_id]" } },
    { id: "discord_add_reaction", name: { fr: "Ajouter une réaction", en: "Add Reaction" }, description: { fr: "Ajoute une réaction à un message", en: "Add a reaction to a message" }, prompt: { fr: "Ajoute la réaction [emoji] au message [message_id] dans [channel_id]", en: "Add reaction [emoji] to message [message_id] in [channel_id]" } },
    { id: "discord_create_channel", name: { fr: "Créer un canal", en: "Create Channel" }, description: { fr: "Crée un nouveau canal", en: "Create a new channel" }, prompt: { fr: "Crée un canal Discord dans [guild_id] : nom [nom], type [text/voice], catégorie [category_id]", en: "Create a Discord channel in [guild_id]: name [name], type [text/voice], category [category_id]" } },
    { id: "discord_delete_channel", name: { fr: "Supprimer un canal", en: "Delete Channel" }, description: { fr: "Supprime un canal", en: "Delete a channel" }, prompt: { fr: "Supprime le canal Discord [channel_id]", en: "Delete Discord channel [channel_id]" } },
    { id: "discord_create_role", name: { fr: "Créer un rôle", en: "Create Role" }, description: { fr: "Crée un nouveau rôle", en: "Create a new role" }, prompt: { fr: "Crée un rôle Discord dans [guild_id] : nom [nom], couleur [hex], permissions [perms]", en: "Create a Discord role in [guild_id]: name [name], color [hex], permissions [perms]" } },
    { id: "discord_assign_role", name: { fr: "Assigner un rôle", en: "Assign Role" }, description: { fr: "Assigne un rôle à un membre", en: "Assign a role to a member" }, prompt: { fr: "Assigne le rôle [role_id] au membre [user_id] dans [guild_id]", en: "Assign role [role_id] to member [user_id] in [guild_id]" } },
    { id: "discord_remove_role", name: { fr: "Retirer un rôle", en: "Remove Role" }, description: { fr: "Retire un rôle d'un membre", en: "Remove a role from a member" }, prompt: { fr: "Retire le rôle [role_id] du membre [user_id] dans [guild_id]", en: "Remove role [role_id] from member [user_id] in [guild_id]" } },
    { id: "discord_ban_member", name: { fr: "Bannir un membre", en: "Ban Member" }, description: { fr: "Bannit un membre du serveur", en: "Ban a member from the server" }, prompt: { fr: "Bannit l'utilisateur [user_id] du serveur [guild_id] pour : [raison]", en: "Ban user [user_id] from server [guild_id] for: [reason]" } },
    { id: "discord_kick_member", name: { fr: "Expulser un membre", en: "Kick Member" }, description: { fr: "Expulse un membre du serveur", en: "Kick a member from the server" }, prompt: { fr: "Expulse l'utilisateur [user_id] du serveur [guild_id]", en: "Kick user [user_id] from server [guild_id]" } },
    { id: "discord_get_member", name: { fr: "Récupérer un membre", en: "Get Member" }, description: { fr: "Récupère les infos d'un membre", en: "Get member info" }, prompt: { fr: "Récupère les informations du membre [user_id] dans [guild_id]", en: "Get information for member [user_id] in [guild_id]" } },
    { id: "discord_list_members", name: { fr: "Lister les membres", en: "List Members" }, description: { fr: "Liste les membres d'un serveur", en: "List server members" }, prompt: { fr: "Liste les membres du serveur [guild_id], limite [nombre]", en: "List members of server [guild_id], limit [number]" } },
  ],
};

// Get specific actions for an integration, falls back to defaults if not found
export const getActionsForIntegration = (slug: string, integrationName: string): IntegrationAction[] => {
  const specific = comprehensiveActions[slug];
  if (specific && specific.length > 0) return specific;
  
  // Generate default actions
  return generateDefaultActionsForSlug(slug, integrationName);
};

const generateDefaultActionsForSlug = (slug: string, name: string): IntegrationAction[] => {
  return [
    { id: `${slug}_create`, name: { fr: "Créer", en: "Create" }, description: { fr: `Crée un élément dans ${name}`, en: `Create an item in ${name}` }, prompt: { fr: `Crée un nouvel élément dans ${name} avec : [paramètres]`, en: `Create a new item in ${name} with: [parameters]` } },
    { id: `${slug}_get`, name: { fr: "Récupérer", en: "Get" }, description: { fr: `Récupère des données depuis ${name}`, en: `Retrieve data from ${name}` }, prompt: { fr: `Récupère [élément] depuis ${name} avec l'ID [id]`, en: `Retrieve [item] from ${name} with ID [id]` } },
    { id: `${slug}_update`, name: { fr: "Mettre à jour", en: "Update" }, description: { fr: `Met à jour un élément dans ${name}`, en: `Update an item in ${name}` }, prompt: { fr: `Mets à jour [élément] dans ${name} avec : [nouvelles valeurs]`, en: `Update [item] in ${name} with: [new values]` } },
    { id: `${slug}_delete`, name: { fr: "Supprimer", en: "Delete" }, description: { fr: `Supprime un élément de ${name}`, en: `Delete an item from ${name}` }, prompt: { fr: `Supprime [élément] de ${name}`, en: `Delete [item] from ${name}` } },
    { id: `${slug}_list`, name: { fr: "Lister", en: "List" }, description: { fr: `Liste les éléments de ${name}`, en: `List items from ${name}` }, prompt: { fr: `Liste les éléments de ${name} avec filtre : [critères]`, en: `List items from ${name} with filter: [criteria]` } },
    { id: `${slug}_search`, name: { fr: "Rechercher", en: "Search" }, description: { fr: `Recherche dans ${name}`, en: `Search in ${name}` }, prompt: { fr: `Recherche dans ${name} : [terme de recherche]`, en: `Search in ${name}: [search term]` } },
  ];
};
